version: '3.2'

services:
  redis:
    image: redis:7.0-bullseye
  
  php-cli:
    image: dynamonet/php:7.3
    command: php -S 0.0.0.0:18080 -t .
    working_dir: /usr/local/app
    volumes:
      - ".:/usr/local/app"